# Generated by Django 4.2 on 2023-09-04 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_image',
            field=models.ImageField(blank=True, default='accounts/profile_images/user.png', null=True, upload_to='accounts/profile_images/'),
        ),
    ]
